### ISSUE TITLE
Example Collection

### ISSUE THREAD

**Issue by waywaaard** [waywaaard/skulpt_numpy#23]
This is an meta issue for collecting code snippets that should run using `skulpt_numpy`.

Neural Network [See blog post](http://iamtrask.github.io/2015/07/12/basic-python-network/):
- [x] `test/2LayerNeuralNetwork.py`
- [x] `test/3LayerNeuralNetwork.py`
 - [x] numpy.mean
 - [x] numpy.abs is the same as numpy.absolute (so we need to map the names) [Docs](http://docs.scipy.org/doc/numpy/reference/generated/numpy.absolute.html)
 - [x] ndarray.dot 
 - [x] ndarray.T 
- [x] Hinton's Dropout in 3 Lines of Python
 - [x] numpy.random.binomial

**Comment by eah13** [comment]
This one uses the *= operator and np.random.binomial
http://iamtrask.github.io/2015/07/28/dropout/

I think we've gotten this one down:
http://iamtrask.github.io/2015/07/27/python-network-part2/

**Comment by eah13** [comment]
Skulpt thing: `from x import y [as z]`

**Comment by eah13** [comment]
- [ ] pull request to trinket for the distfile
