### ISSUE TITLE
Numpy Random Module

### ISSUE THREAD

**Issue by waywaaard** [waywaaard/skulpt_numpy#4]
Coordination issuse for the random function stack in numpy.

Reference impl.: https://github.com/numpy/numpy/tree/master/numpy/random/mtrand

## Todo
- [x] Implement numpy mersenne twister algorithm and expose required internal variables. See ```randomkit.c``` for implementation details
- [x] test randomkit.js functions (first tests have been successful)
- [x] Implement ```initarray.c```
- [x] Add ```mtrand``` infrastructure
- [x] Add ```RandomState``` class (this contains the complete random functions
- [x] Add ```_rand``` this is an instance of ```RandomState```
- [x] Implement first version of numpy.random.rand from ```https://github.com/numpy/numpy/blob/master/numpy/random/mtrand/mtrand.pyx```
- [x] Implement ```distributions.c``` functions
- [x] Complementary work?

## Issues for implementation
- [ ] figure out how skulpt can be fixed for imports like
```python
from numpy import random
```

**Comment by waywaaard** [comment]
see ```random/README.md``` for more information

**Comment by waywaaard** [comment]
The impl. of the distribution functions may be opened in a own issue
